/**
 * Markdown report generator for contract failures
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import type { VerificationResult } from './types.js';
import type { Expectation } from '@saync/core';

/**
 * Write a markdown report for a failed contract verification
 */
export async function writeMarkdownReport(
  result: VerificationResult,
  expectation: Expectation,
  outputDir: string = './saync-reports'
): Promise<void> {
  if (result.passed) {
    return; // Only write reports for failures
  }

  // Ensure output directory exists
  await mkdir(outputDir, { recursive: true });

  // Generate filename from contract name
  const filename = expectation.id
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  
  const filepath = join(outputDir, `${filename}.md`);

  // Build markdown content
  const content = generateMarkdownContent(result, expectation);

  await writeFile(filepath, content, 'utf-8');
}

/**
 * Generate markdown content for a failure report
 */
function generateMarkdownContent(
  result: VerificationResult,
  expectation: Expectation
): string {
  const lines: string[] = [];

  // Frontmatter
  lines.push('---');
  lines.push(`title: "${expectation.id} - Contract Violation"`);
  lines.push(`severity: ${determineSeverity(result)}`);
  lines.push(`contractId: ${expectation.id}`);
  lines.push(`timestamp: ${result.timestamp}`);
  lines.push(`status: open`);
  lines.push('---');
  lines.push('');

  // Summary
  lines.push('# Contract Violation Report');
  lines.push('');
  lines.push(`**Contract:** \`${expectation.id}\``);
  lines.push(`**Type:** ${expectation.type}`);
  lines.push(`**Duration:** ${result.duration}ms`);
  lines.push('');

  // Errors
  if (result.errors.length > 0) {
    lines.push('## Errors');
    lines.push('');

    for (const error of result.errors) {
      lines.push(`### ${error.type}`);
      lines.push('');
      lines.push(error.message);
      lines.push('');

      if (error.expected !== undefined) {
        lines.push('**Expected:**');
        lines.push('```');
        lines.push(formatValue(error.expected));
        lines.push('```');
        lines.push('');
      }

      if (error.actual !== undefined) {
        lines.push('**Actual:**');
        lines.push('```');
        lines.push(formatValue(error.actual));
        lines.push('```');
        lines.push('');
      }

      if (error.stack) {
        lines.push('<details>');
        lines.push('<summary>Stack Trace</summary>');
        lines.push('');
        lines.push('```');
        lines.push(error.stack);
        lines.push('```');
        lines.push('</details>');
        lines.push('');
      }
    }
  }

  // Contract details
  lines.push('## Contract Details');
  lines.push('');
  lines.push('```json');
  lines.push(JSON.stringify(expectation, null, 2));
  lines.push('```');
  lines.push('');

  // Screenshot
  if (result.screenshot) {
    lines.push('## Screenshot');
    lines.push('');
    lines.push('![Failure Screenshot](data:image/png;base64,' + result.screenshot + ')');
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Saync Agent*');
  lines.push('');

  return lines.join('\n');
}

/**
 * Determine severity based on error types
 */
function determineSeverity(result: VerificationResult): string {
  const errorTypes = result.errors.map(e => e.type);

  if (errorTypes.includes('timeout')) {
    return 'high';
  }
  if (errorTypes.includes('api-call')) {
    return 'critical';
  }
  if (errorTypes.includes('response-shape')) {
    return 'high';
  }
  if (errorTypes.includes('selector-not-found')) {
    return 'critical';
  }

  return 'medium';
}

/**
 * Format a value for display
 */
function formatValue(value: unknown): string {
  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'object') {
    return JSON.stringify(value, null, 2);
  }
  return String(value);
}

// Made with Bob